version: '3'
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=apaWS_DB
  api:
    build: .
    restart: always
    container_name: apa-api
    ports:
      - '8080:8080'
    depends_on:
      - db