version: '3'
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=apaWS_DB
    networks:
      - apa-backend
  api:
    build: .
    restart: always
    networks:
      - apa-backend
    container_name: apa-api
    ports:
      - 8080:8080
    depends_on:
      - db
    image: tomcat
    volumes:
      - ./target/apa.war:/usr/local/tomcat/webapps/apa.war

networks:
  apa-backend:
    driver: bridge
